### ISSUE TITLE
GUI High DPI support

### ISSUE THREAD

**Issue by sassy-or-clement** [Telltale-Modding-Group/Telltale-Script-Editor#8]
The current version Alpha 1.1.0 seems to have an issue with non 100% scaling of the UI in Windows 10.

The issue looks as follows on a screen with 150% scaling (note the difference between the window title font and the font in the row below):
<img width="601" alt="gui_scaling_bad" src="https://user-images.githubusercontent.com/78814070/109533769-dfab8e00-7aba-11eb-983b-24917283273d.png">

By using the [high DPI support](https://docs.microsoft.com/en-us/dotnet/desktop/winforms/high-dpi-support-in-windows-forms?view=netframeworkdesktop-4.8) starting with .Net 4.7, I tested the following settings in the `App.config`:

```xml
<System.Windows.Forms.ApplicationConfigurationSection>
	<add key="DpiAwareness" value="PerMonitorV2" />
	<add key="EnableWindowsFormsHighDpiAutoResizing" value="false" />
</System.Windows.Forms.ApplicationConfigurationSection>
```

This results in the following and more appealing font rendering:
<img width="601" alt="gui_scaling_correct" src="https://user-images.githubusercontent.com/78814070/109534315-82640c80-7abb-11eb-9aa0-1b49caa817c9.png">

Note the difference in layout on the left column. The difference in scaling messes up the layout of dialogs.
Current:
<img width="364" alt="gui_scaling_bad_dialog" src="https://user-images.githubusercontent.com/78814070/109534589-c9520200-7abb-11eb-901e-e9f9e1c549e9.png">

With the above changes to the `App.config`:
<img width="364" alt="gui_scaling_correct_dialog" src="https://user-images.githubusercontent.com/78814070/109534623-d40c9700-7abb-11eb-8c8d-c77129bbf5f8.png">

The small adjustment in the `App.config` does not seem to be enough for fixing this issue. Is there any interest in fixing this, as it does not impact the functionality of the software?
If there is any interest, I'd volunteer to look deeper into the issue and try to come up with something that does not include any regressions.

**Comment by frostbone25** [comment]
There is still interest in this project. However, I've been mostly working heavily on the rewrite branch of the software which basically revamps the whole software and is rewritten in WPF instead of Forms. Along with that, it contains a lot more features and better overall usability and presentation, and it's nearing completion. So for the time being, the public branch isn't a huge priority as it all mostly works as intended minus the issues you mentioned of course. **But with that said you are totally free to fork and push a change to the public branch.** There are a few little things as well that I would love to add to make useability a little better on the public branch, but yeah violet will get with you about it as well. Thanks for posting this mate!

**Comment by sassy-or-clement** [comment]
> I've been mostly working heavily on the rewrite branch of the software which basically revamps the whole software and is rewritten in WPF instead of Forms

Ok, that probably puts the priority of this issue quite low. I took a quick look into the source code and saw a bunch of hard-coded layouts. Redoing this, would likely require a bunch of tweaking that is quite time consuming. So for the time being (and because this is merely a quality of life improvment for my eyes) I won't work on this.

> But with that said you are totally free to fork and push a change to the public branch

Well, at least I found a bug (exception). Will post a pull request in a couple of days.

I will close this issue for now, feel free to open it again if necessary.
